runtime: python311

entrypoint: gunicorn -b :$PORT app:app

instance_class: F1  # lowest-cost instance, perfect for portfolio

automatic_scaling:
  max_instances: 2  # keep costs and scaling under control

env_variables:
  FLASK_ENV: production
  SECRET_KEY: 'your-strong-secret-key'

handlers:
  - url: /.*
    script: auto
